use dmll_sql;
show tables;
SELECT * FROM EMPLOYEE_OLD;
SELECT * FROM employee_old WHERE SALARY<>(SELECT AVG(SALARY)FROM employee_old);
SELECT AVG(SALARY) FROM employee_old;
SELECT * FROM employee_old WHERE SALARY<>(SELECT AVG(SALARY)FROM employee_old);
SELECT SALARY FROM employee_old WHERE EMP_ID='3';
### NESTED QUERY #####
SELECT * FROM employee_old WHERE SALARY > (SELECT SALARY FROM employee_old WHERE emp_id='2');


#####  VIEWS  ########
USE VARDHAN;
SELECT * FROM INDEX_1;
SELECT * FROM INDEX_1 WHERE CASH_TYPE='CASH';

SELECT * FROM INDEX_1 WHERE COFFEE_NAME='LATTE';

CREATE VIEW LATTE1 AS SELECT*FROM INDEX_1 WHERE COFFEE_NAME='LATTE';

SELECT * FROM LATTE1;

SELECT * FROM CHURN;
SELECT * FROM CHURN WHERE GENDER='FEMALE';
CREATE VIEW CHURN_FEMALE1 AS SELECT * FROM CHURN WHERE GENDER='FEMALE';

SELECT * FROM CHURN_FEMALE1;
DESC CHURN;
ALTER TABLE CHURN DROP COLUMN Exited;
